name: calc
description: "A new Flutter project."
publish_to: 'none' # Prevents the package from being published to pub.dev

version: 1.0.0+1 # Version number and build number

environment:
  sdk: ^3.5.4 # Dart SDK version

dependencies:
  flutter:
    sdk: flutter # Dependency on the Flutter SDK
  cupertino_icons: ^1.0.8 # Cupertino icons for iOS style

dev_dependencies:
  flutter_test:
    sdk: flutter # Dependency for Flutter testing
  flutter_lints: ^4.0.0 # Recommended lints for good coding practices

flutter:
  uses-material-design: true # Enables Material Design icons
  assets: # List of asset files
    - assets/images/app_logo.png # Path to the app logo image

# Additional comments about Flutter package structure can be added here